export const DEFAULT_PROGRAM = `; Alset-LISPAI — UI como datos
(do
  (theme (primary "#E8C547") (background "#0B0E14") (surface "#151B26"))
  (def title "Hola desde LispAI")
  (gene "ui-pulse" (log "gene ui-pulse registrado"))
  (agent "preview-agent")
  (rootcid (list title "v0.1"))
  (mind-note "UI simbolica lista")
  (ui
    (column (pad 8) (gap 12)
      (card (pad 16) (gap 8)
        (text title (size 22) (weight bold) (color primary))
        (text "Runtime declarativo · sin recomposicion total del DOM" (size 13) (color muted))
      )
      (row (gap 10) (wrap true)
        (button "Probar click" (pad 12) (on-click "ping"))
        (button "Mobile first" (pad 12) (bg secondary))
      )
      (card (pad 14)
        (text "Edita el Lisp, ejecuta, inspecciona el arbol y la consola." (size 13) (color muted))
      )
    )
  )
)
`;
